import { Platform } from "react-native";

function themed(name: string, fallback: string) {
  return Platform.OS === "web" ? `var(--meetfair-${name}, ${fallback})` : fallback;
}

export const colors = {
  background: themed("background", "#F7F8FC"),
  surface: themed("surface", "#FFFFFF"),
  surfaceSubtle: themed("surface-subtle", "#F1F3F9"),
  surfaceHover: themed("surface-hover", "#FAFAFF"),
  text: themed("text", "#171923"),
  textSecondary: themed("text-secondary", "#3F4350"),
  muted: themed("muted", "#697080"),
  subtle: themed("subtle", "#A0A5B1"),
  icon: themed("icon", "#626978"),
  border: themed("border", "#EAECF2"),
  borderStrong: themed("border-strong", "#C7D2FE"),
  input: themed("input", "#FFFFFF"),
  primary: themed("primary", "#5B5FEA"),
  primaryHover: themed("primary-hover", "#4F46E5"),
  primaryPressed: themed("primary-pressed", "#4338CA"),
  primarySoft: themed("primary-soft", "#EEF2FF"),
  primaryContrast: themed("primary-contrast", "#FFFFFF"),
  focusRing: themed("focus-ring", "rgba(99,102,241,0.28)"),
  disabled: themed("disabled", "#A0A5B1"),
  mint: themed("mint", "#ECFDF3"),
  green: themed("green", "#16794A"),
  online: themed("online", "#22C55E"),
  success: themed("success", "#16794A"),
  successSoft: themed("success-soft", "#ECFDF3"),
  successBorder: themed("success-border", "#BBF7D0"),
  amber: themed("amber", "#A15C07"),
  amberSoft: themed("amber-soft", "#FFF7E8"),
  warning: themed("warning", "#A15C07"),
  warningSoft: themed("warning-soft", "#FFF7E8"),
  warningBorder: themed("warning-border", "#FDE3AE"),
  red: themed("red", "#BE123C"),
  redSoft: themed("red-soft", "#FFF1F2"),
  danger: themed("danger", "#BE123C"),
  dangerSoft: themed("danger-soft", "#FFF1F2"),
  dangerBorder: themed("danger-border", "#FECDD3"),
  blue: themed("blue", "#4338CA"),
  blueSoft: themed("blue-soft", "#EEF2FF"),
  charcoal: themed("charcoal", "#171923"),
  header: themed("header", "rgba(255,255,255,0.92)"),
  navActive: themed("nav-active", "#EEF2FF"),
  shadowCard: themed("shadow-card", "rgba(31,35,48,0.10)"),
  shadowFloating: themed("shadow-floating", "rgba(31,35,48,0.16)"),
} as const;
